sources:
  - id: api1
    path: scripts
    main: etl_example.py
    params:
      url: "https://api1.com/data"
      output_path: "api1.csv"
    dependencies: requirements.txt
    kernel: python3
  - id: web2
    path: notebooks
    main: etl_example.ipynb
    params:
      selector: ".value"
      output_path: "web2.json"
    dependencies: requirements.txt
    kernel: python3