sources:
  - id: api1
    path: scripts
    main: etl_example.py
    params:
      url: "https://api1.com/data"
      output_path: "data/api1.csv"
  - id: web2
    path: notebooks
    main: etl_example.ipynb
    params:
      selector: ".value"
      output_path: "data/web2.json"
