name: ETL matrix

on:
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [api1, web2]
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar ETL Runner
        uses: andres-chirinos/etl-runner-action@v0.0.8
        with:
          source: ${{ matrix.source }}
          config-path: etl_config.yaml
          out-dir: outputs/${{ matrix.source }}

      - name: Subir resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultado-${{ matrix.source }}
          path: outputs/${{ matrix.source }}

      - name: Mostrar archivos generados
        run: |
          ls -lh outputs/${{ matrix.source }}

      - name: Verificar contenido de salida
        run: |
          head -n 20 outputs/${{ matrix.source }}/* || echo "No hay archivos para mostrar"
